### ISSUE TITLE
[meta] Tracking issue for r0.1.2 compatibility

### ISSUE THREAD

**Issue by Nauxuron** [ruma/ruma-appservice-api#2]
- [x] `/_matrix/app/v1/thirdparty/*` endpoints. Currently waiting until ruma/ruma-client-api#44 can be merged.
- [x] `PUT /_matrix/client/r0/directory/list/appservice/{networkId}/{roomId}`. This endpoint needs to be added to the client API, but can only be used by an application service. (ruma/ruma-client-api#45)
- [x] ruma-client needs to support the `user_id` query parameter for every endpoint so that the application service can act as a certain user within its user namespace. (ruma/ruma-client#27)
- [x] The client should allow specifying the `as_token` as `access_token`. (ruma/ruma-client#27)
